### ISSUE TITLE
Blank Page after trying to load an image for a badge

### ISSUE THREAD

**Issue by stroes** [ITPrism/GamificationPlatform#12]
Hi, 

Are there any requirements to the images like max size? every time i try to load an image for a badge i get a blank page?

Thanks

**Comment by quende** [comment]
Hello,

look here https://github.com/ITPrism/GamificationPlatform/issues/7#issuecomment-100798968

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!

The problem comes from changes in File classes.
https://github.com/ITPrism/ITPrismLibrary/tree/master/file

I use them in the method "[uploadImage] (https://github.com/ITPrism/GamificationPlatform/blob/master/admin/models/badge.php#L169)".

If you edit those methods, you will be able to upload pictures.

However, I have rewritten whole platform and I am going to publish it soon. So, it will be fixed.

**Comment by stroes** [comment]
Hi, 

Apologies for the late reply. what is the possibility of me getting early access to the new platform you have rewritten. 

I am busy comparing different gamification options to use and really need to decide on one. I like yours the most so far as it integrates with Joomla and Jomsocial which is ideal for the systems i am busy building. 

I look forward to hearing from you soon. 

Regards
Peter

**Comment by khajuriaraj** [comment]
When the new platform will be published ??

**Comment by Foxmillet** [comment]
Hi, Teodor!

Are there any news about the new version of the platform?

Thanks in advance!!

**Comment by ITPrism** [comment]
Hi,
I will definitely publish it this month.

Best regards,
Todor
